#!/bin/sh

# Other aliases

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#some custom aliases
alias bat='bat  --color=always ' # --style=numbers,changes,header'
alias cbr="cargo build --release"
alias cdr='cd;clear'
alias chtsh='cht.sh'
alias cp='cp -vr'
alias cr='clear'
alias df='df -h'
alias du='du --apparent-size -h'
alias dust='dust -sp'
alias fm='vifm .'
alias free='free -m'
alias loc='loc | ccat'
alias lpv='lolcat /proc/version'
alias mkdir='mkdir -pv'
alias mv='mv -vi'
alias pwd='pwd -P'
alias rm='rm -rfv'
alias sa='source $HOME/aliases/aliases'
alias sdn='shutdown now'
alias sh='dash'
alias tail='tail -v'
alias tar="tar -xvf"
alias tokei='tokei | ccat'
alias top="htop"
alias tree='tree --si --du'
alias uname='uname -a | lolcat'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias wcl='wc -l'
alias wcw='wc -w'
alias wtf='wtfutil > /dev/null'
alias tfetch='tfetch | lolcat -h 1 -v 1'
alias prettier='npx prettier'
alias p='python'
alias grm='go run ./main.go'
alias start='pnpm start'
alias pnpm-upgrade='pnpm add -g @pnpm/exe'
alias vimf='vim $(fzf-tmux --preview "bat --style=numbers --color=always --line-range :500 {}")'
alias scc='scc -c --no-size --no-cocomo'

source <(cat $HOME/aliases/*.sh)
